CKPT_EVERY_N_SECONDS = 60
UPDATE_DEMONSTRATION_LOSSES_EVERY_N_SECONDS = 30
DEFAULT_BC_COEF = 10
DEFAULT_ENT_COEF = 0.01
FRAMES_PER_SEGMENT = 30
DEFAULT_ROLLOUT_LEN_SECONDS = 1.0
ROLLOUT_FPS = 30
MAX_PREFS = 3000
